name: Dev Release
on: [push, workflow_dispatch]

permissions:
  contents: write

env:
  BUILD_TYPE: Release
jobs:
  dev-release:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [release-no-debug-msvc]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "3.31.6"

      - name: Get version
        id: get_version
        run: |
          $Version = if ($env:GITHUB_REF -match "refs/tags/(.*)") { $matches[1] } else { "dev" }
          echo "version=$Version" >> $env:GITHUB_OUTPUT

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset=build-${{matrix.preset}}
        env:
          CMAKE_BUILD_TYPE: Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build/build-${{matrix.preset}} --config Release

      - name: Create Package
        run: |
          $Version = "${{ steps.get_version.outputs.version }}"
          $OpenXRZipName = "gowrk-vr-openxr-$Version"
          $OpenVRZipName = "gowrk-vr-openvr-$Version"
          
          # Create package directories
          mkdir ${{github.workspace}}/package-openxr
          mkdir ${{github.workspace}}/package-openvr
          mkdir ${{github.workspace}}/symbols
          
          # Copy OpenXR release files
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.dll" "${{github.workspace}}/package-openxr/"
          
          # Copy OpenVR release files
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.dll" "${{github.workspace}}/package-openvr/"
          Copy-Item "${{github.workspace}}/shipping/openvr_api.dll" "${{github.workspace}}/package-openvr/"
          
          # Copy debug symbols
          # Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.pdb" "${{github.workspace}}/symbols/"
          Copy-Item "${{github.workspace}}/build/build-${{matrix.preset}}/Release/dxgi.dll" "${{github.workspace}}/symbols/"
          
          # Create packages
          7z a "${{github.workspace}}/$OpenXRZipName.zip" "${{github.workspace}}/package-openxr/*"
          7z a "${{github.workspace}}/$OpenVRZipName.zip" "${{github.workspace}}/package-openvr/*"
          7z a "${{github.workspace}}/$OpenXRZipName-symbols.zip" "${{github.workspace}}/symbols/*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gowrk-vr-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OpenXR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-openxr-${{ steps.get_version.outputs.version }}
          path: ${{github.workspace}}/package-openxr/*
          if-no-files-found: error

      - name: Upload OpenVR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-openvr-${{ steps.get_version.outputs.version }}
          path: ${{github.workspace}}/package-openvr/*
          if-no-files-found: error

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-${{ steps.get_version.outputs.version }}-symbols
          path: ${{github.workspace}}/symbols/*
          if-no-files-found: error
